# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Techtown Portland Diversity Survey 2016
email: hello@planetargon.com
description: > # this means to ignore newlines until "baseurl:"
  A survey representing the state of diversity in Portland's Tech Industry in 2016. The data is collected from 23 companies signing a pledge to further diversity in tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
